### PR TITLE
Hot path analysis

### PR DESCRIPTION
**Pull request by edespong**
This PR does not contain a feature-complete hotpath analysis as discussed in #7 and #33. Rather it is a fully working start with a very limited feature set:
* Added the PerformanceCriticalAttribute to its own assembly. This assembly should be released as a separate package so that users only need to reference it rather than the current package
* Members marked with this attribute will enable analysis for all rules within that method with the default severities
* If one member in a class is marked, no unmarked members of that class will be analyzed
* If a class does not have any method with the attribute, analysis is done on every method (default, old behavior)

The PR does not add the ability to specify specific rules to be enabled or change the severity for them but it lays a foundation for it.

### CODE REVIEW

**Comment by sharwell** [comment]
Hi @edespong,

I work over on dotnet/roslyn, and earlier today @mjsabby pointed my team to this pull request. In Roslyn, we created [PerformanceSensitiveAttribute](https://github.com/dotnet/roslyn/blob/45aa7a2de7cef7e527ad93b9b9df2c3acb2e30ac/src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs) a while back, and this week started looking into leveraging RoslynClrHeapAllocationAnalyzer to enforce the constraints documented by that attribute. We started by creating a modified copy of this analyzer in dotnet/roslyn-analyzers (see dotnet/roslyn-analyzers#2117), and now we're starting work to focus on specific constraint validation.

There are a few differences between the implementation in this pull request and the way our team's attribute is intended to work (e.g. limiting specific operations), but we're hoping the design works well enough that other teams are able to leverage it as well. Would you be willing to take a look at the attribute and let us know if targeted enforcement of that attribute would be a suitable alternative for you?

Thanks! 😄

**Comment by edespong** [comment]
@sharwell 

Would it be correct to assume that the attribute would be part of a larger package that would need referenced to be used, or will it be quite standalone? If the former, I would probably not use it for this project as any user would have to take on a big dependency for just that attribute.

I do not know if you agree with this @mjsabby, but it seems like a lot of (potential) users of this project would prefer that when we add an attribute to signal a hot path, that it would make sense to reverse the logic of the whole project and only analyze the methods annotated with those attributes. 
 
If so, I do not think that there is an absolute need for an advanced attribute where you can be granular about what should and should not be allowed. If you have allocations that are in an annotated method, you should be able to turn off any warning with a `#pragma`.

**Comment by sharwell** [comment]
@edespong the attribute would be added as a single source file to the build and compile as an `internal` type. It would not result in any new dependencies.

It sounds like we are on the same page at a high level, though we may need to make some adjustments to the final design based on usability feedback.

**Comment by drewnoakes** [comment]
The attribute could also be defined as `[Conditional("PERFORMANCE_ANNOTATIONS")]` or similar, so they don't increase compiled binary size if not needed (I can't see why they'd be needed in binaries).

**Comment by sharwell** [comment]
@drewnoakes It is: 😄 
https://github.com/dotnet/roslyn-analyzers/blob/33b7110494aebe7d2ddde305f1905c6c42423e19/nuget/PerformanceSensitive.Analyzers/PerformanceSensitiveAttribute.cs#L18

**Comment by jaredpar** [comment]
Thanks for your contribution here. Unfortunately this project is no longer maintained. The high impact analyzers from this repository are being merged with [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers). As such, the active PRs are being closed and this repo is being archived.

**Pull request closed without merging**
