### PR TITLE
Options for Visual Studio usage

### PR DESCRIPTION
**Pull request by edespong**
Solves #22

Large changes:
* A new menu called Heap Allocation Analuzer under Options (see screenshot).
* Settings are saved with the WritableSettingsStore into the registry.
* The options page is placed in the Vsix project and need knowledge of what rules and severities are. Thus, all common stuff was pulled out to a new project that is referenced by both Vsix and the main project.
* I had to change project from .NET standard to standard .NET because I could not get the config API to work otherwise.

Current limitations:
* Minimal testing done on real projects.
* Right now you have to either do a change (adding a space and deleting it is enough) in a file or close/re-open in order for the new settings to start working. It would be nice to trigger a re-analysis on Apply.
* There could be more unit tests.
* Few comments explaining the code (though no worse than the solution in general).
* Because of the change back to standard .NET, it seems like some of the settings of the projects are not what they were before.

screengrab

### CODE REVIEW

**Comment by mjsabby** [comment]
@edespong This is a pretty big change :) It'll take some time to review. What I'll do is prepare a new package for the analyzer now that we've fixed some nice issues and then take a look at this.

In the mean time is there a way we can separate out the VS-specific part into a different assembly?

**Comment by edespong** [comment]
@mjsabby Yes, it grew quite large and I think it touches almost every file in the solution due to its nature of checking if a check is enabled or not.

I see that I have hade a misstake and included the concrete class which references the WritableSettingsStore in the Common project. This should really be in the Vsix project and I will fix that right away.

Can you be more specific in what you mean about VS-specific? For example, the common project references the Microsoft.CodeAnalysis.DiagnosticSeverity enum. If that is an issue, I can create an intermediary enum with the same values used for communication.

**Comment by edespong** [comment]
Turns out it was not trivial as the unit tests dependended on the HeapAllocationAnalyzerSettings and I do not want the unit test project to reference the Vsix project.

**Comment by CianNoonan** [comment]
Has there been any update on this PR? This feature would be a huge QoL improvement for my use case

**Comment by edespong** [comment]
> 
> 
> Has there been any update on this PR? This feature would be a huge QoL improvement for my use case

Based on the discussions in the other issue threads, I think this PR is effectively dead. 

If you do not need the actual options but rather just want to have a different set of rules enabled/other types of warnings, it is very easy to just pull the source from master, changing the `DiagnosticDescriptor` for the rules you want and do a build.

**Comment by CianNoonan** [comment]
I've actually just built from your branch and used that, it meets my needs currently. It's a shame because it really helps to be able to quickly toggle some of these. 

Thanks for your work anyway, even if the PR is dead the branch its self is still very helpful

**Comment by mjsabby** [comment]
Thanks @edespong for the effort on this one. With the PR in OmniSharp (https://github.com/OmniSharp/omnisharp-roslyn/pull/1076) we should be able use the other thing you're working on with VS AND VSCode, which is a big win.

**Pull request closed without merging**
